# Generated by Django 4.1.3 on 2023-03-23 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programm_path', models.CharField(help_text='путь до программы', max_length=60, validators=[django.core.validators.MinLengthValidator(2, message='Убедитесь, что длина пути более 2 символов')], verbose_name='путь до программы chirp.py')),
                ('programm_config_path', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2, message='Убедитесь, что длина пути более 2 символов')], verbose_name='путь до файла настроек')),
                ('storage_path', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2, message='Убедитесь, что длина пути более 2 символов')], verbose_name='путь записи ионограмм')),
                ('sample_rate', models.IntegerField()),
                ('filter', models.BooleanField()),
                ('filter_band', models.IntegerField()),
                ('sample_count', models.IntegerField()),
                ('decimation', models.IntegerField()),
                ('fft_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(1, message='Убедитесь, в названии есть хотя бы 1 символ')], verbose_name='Название расписания')),
                ('start_date_time', models.DateTimeField()),
                ('stop_date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Swtracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Конфигурация трассы для зондирования.')),
                ('receive_station', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2, message='Убедитесь, что длина названия содержит хотя бы 2 символа.')], verbose_name='Название приёмной станции')),
                ('transmit_station', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(2, message='Убедитесь, что длина названия содержит хотя бы 2 символа.')], verbose_name='Название передающей станции')),
                ('repetition_period', models.IntegerField(verbose_name='Период повторения сеанса зондирования.')),
                ('chirptime', models.IntegerField(verbose_name='Время начала синтеза ЛЧМ сигнала с 0 МГц.')),
                ('adjust_speed', models.IntegerField(verbose_name='Корректировка скорости ЛЧМ.')),
                ('session_duration', models.IntegerField(verbose_name='Длительность сеанса.')),
                ('heterodyne_frequency', models.IntegerField(verbose_name='Частота гетеродина.')),
                ('latitude', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Широта.')),
                ('longitude', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Долгота.')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
