# Generated by Django 4.1.3 on 2023-04-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirpsounder', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulesettings',
            old_name='owner',
            new_name='author',
        ),
    ]
